### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dadevguy** [Cattodevelopment/betterminion-pm4#1]
# Stack Traces

[15:03:46.345] [Server thread/INFO]: Loading BetterMinion v0.0.1
[15:03:46.832] [Server thread/CRITICAL]: pocketmine\lang\LanguageNotFoundException: "Language "eng" not found" (EXCEPTION) in "pmsrc/src/lang/Language" at line 130
--- Stack trace ---
  #0 pmsrc/src/lang/Language(108): pocketmine\lang\Language::loadLang(string[46] /home/container/plugin_data/BetterMinion/langs, string[3] eng)
  #1 plugins/betterminion-pm4-master-pm4.phar/src/utils/Language(34): pocketmine\lang\Language->__construct(string[3] eng, string[46] /home/container/plugin_data/BetterMinion/langs)
  #2 plugins/betterminion-pm4-master-pm4.phar/src/BetterMinion(43): Mcbeany\BetterMinion\utils\Language::load()
  #3 pmsrc/src/plugin/PluginBase(95): Mcbeany\BetterMinion\BetterMinion->onLoad()
  #4 pmsrc/src/plugin/PluginManager(222): pocketmine\plugin\PluginBase->__construct(object pocketmine\plugin\PharPluginLoader#24867, object pocketmine\Server#10, object pocketmine\plugin\PluginDescription#24966, string[40] /home/container/plugin_data/BetterMinion, string[63] phar:///home/container/plugins/betterminion-pm4-master-pm4.phar, object pocketmine\plugin\DiskResourceProvider#25372)
  #5 pmsrc/src/plugin/PluginManager(364): pocketmine\plugin\PluginManager->internalLoadPlugin(string[56] /home/container/plugins/betterminion-pm4-master-pm4.phar, object pocketmine\plugin\PharPluginLoader#24867, object pocketmine\plugin\PluginDescription#24966)
  #6 pmsrc/src/Server(1006): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/)
  #7 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #8 pmsrc/src/PocketMine(327): pocketmine\server()
  #9 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by RealCatto** [comment]
Sir upload viruons

**Comment by RealCatto** [comment]
Dm me to get them

**Comment by dadevguy** [comment]
done i dont need
